### ISSUE TITLE
Custom fields can't be used in filters - Port D7 Core Custom Field Integration to CiviCRM Entity

### ISSUE THREAD

**Issue by jamie-tillman** [eileenmcnaughton/civicrm_entity#200] opened 2019-12-19 20:45 UTC
To reproduce, create a custom field for Contacts (mine was a multi-valued select list)
Create a view for Contact Entities and add the custom field to the filter (I exposed mine to the user with the default "Is one of" operator)
Execute the view with no filter value selected and it works fine.
Select a filter value and Apply it and you get an error like the following:
```
Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Member Directory[member_directory]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'civicrm_contact.custom_2' in 'where clause': SELECT civicrm_contact.id AS id, contact_id_civicrm_contact.id AS contact_id_civicrm_contact_id FROM {civicrm_contact} civicrm_contact INNER JOIN {civicrm_membership} contact_id_civicrm_contact ON civicrm_contact.id = contact_id_civicrm_contact.contact_id WHERE ((contact_id_civicrm_contact.status_id IN(:civicrm_membership_status_id__0, :civicrm_membership_status_id__1, :civicrm_membership_status_id__2))) AND ((civicrm_contact.custom_2 = :civicrm_contact_custom_2)) LIMIT 21 OFFSET 0; Array ( [:civicrm_contact_custom_2] => Baker [:civicrm_membership_status_id__0] => 1 [:civicrm_membership_status_id__1] => 2 [:civicrm_membership_status_id__2] => 3 ) in Drupal\views\Plugin\views\query\Sql->execute() (line 1543 of core/modules/views/src/Plugin/views/query/Sql.php).
```
It appears that the custom field is being treated as if it were a column in the civicrm_contact table, which is not the case.

**Comment by jackrabbithanna** [comment] 2020-04-01 14:05
Skvare has started working on improved custom field Views integration. There should be a significant PR coming in the next month or so. We are considering porting the entire D7 CiviCRM Core Views handling of custom fields to D8. This could mean breaking changes to those already using CE for D8 Views with custom fields. Anyone interested in this subject should post here or reach out to me. Consider that in the D7, custom fields were treated as a separate table, implicitly joined to the appropriate entity type base table, without a Views Relationship.

**Comment by jamie-tillman** [comment] 2020-04-01 14:31
I'm not sure what the implications of this plan really are, apart from the likelihood of breaking changes.  Overall I'd support any move that gets things to a reliable state.  And I'd be willing to assist with testing since I now have a semi-functioning CE/Views implementation in use on a live site.

I suspect that anyone using CE for D8 at all is probably used to things not working anyway, or having to jump through dozens of hoops and even write/hack code to make it work.  So I'd expect breaking changes that result in proper functioning overall would be a welcome thing.

**Comment by KarinG** [comment] 2020-04-01 15:00
Hey Mark - did you discuss this strategy with @dsnopek - would be great to get his take on this.

**Comment by jackrabbithanna** [comment] 2020-04-01 15:08
@KarinG not yet, starting the discussion here and now. We need custom field handling for filters especially for a number of projects, so it's happening. Definitely want whatever feedback or input we can get. Obviously this will be a large-ish project, but something is better than nothing and we can iterate for the CE general release.

I'm considering making the Views integration work very similar to how it did in D7 .. which means removing the current custom_* Views integration from CivicrmEntityViewsData.php .. then setting up the implicit joins, porting the necessary custom field / filter plugins .. 

Here's some information on how this worked for the D7 Core views integration:
In the D7 version of CiviCRM Core Views handling...

Custom field Views handling is performed by function civicrm_views_custom_data_cache() for an entity type.
https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm.views.inc#L328

civicrm_views_custom_data_cache() is called a number of times, if a CiviCRM component is enabled and it's Views integration built. for instance
https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/components/civicrm.core.inc#L3213

```
// Pull in all the Custom fields
  $query = "select id, extends, extends_entity_column_value, style from civicrm_custom_group where is_active = 1";
  $dao = CRM_Core_DAO::executeQuery($query);
  while ($dao->fetch()) {
    // Call getTree using $dao->id as groupID, $dao->extends as entityType, with possible subtypes in $dao->extends_entity_column_value
    $data = civicrm_views_custom_data_cache($data, $dao->extends, $dao->id, $dao->extends_entity_column_value);
  }
```

So the civicrm_views_custom_data_cache() method does the Views handler per custom field group

Similar logic for this handling will be ported into CivicrmEntityViewsData.php for the D8 version, in the getViewsData() method

For filters specifically, civicrm_views_get_filter() is called to determine which filter handler should be used for a custom field
https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm.views.inc#L395
https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm.views.inc#L576

There, depending on the data_type and html_type of the custom field, a filter handler object is chosen.

There are some Drupal core provided handlers that are used for some types, but some types need special handlers, and we will need to port these.

This task can be for the porting of these Views Filter handlers.

These include:
civicrm_handler_filter_country_multi https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_country_multi.inc
civicrm_handler_filter_state_multi https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_state_multi.inc
civicrm_handler_filter_custom_option https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_custom_option.inc
civicrm_handler_filter_custom_single_option https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_custom_single_option.inc
civicrm_handler_filter_datetime (TBD, can D8's Core datetime filter be used?) https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_datetime.inc
civicrm_handler_filter_pseudo_constant https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_pseudo_constant.inc
civicrm_handler_filter_contact_ref https://github.com/civicrm/civicrm-drupal/blob/7.x-master/modules/views/civicrm/civicrm_handler_filter_contact_ref.inc

Those are all of the D7 Views filter plugins we should need to port to D8 Views filter plugins

**Comment by ddoligalski** [comment] 2020-04-01 17:41
@jackrabbithanna   This would be huge.  We are running into significant issues migrating existing clients that have deep dependencies on D7 views into D8.  Full parity of D7 views to D8 would be ideal.

**Comment by jackrabbithanna** [comment] 2020-04-01 19:06
@ddoligalski  a large part of the reasoning behind feature parity or doing custom fields in a similar way as was done in D7 was to make migration easier. 

@KarinG when we make the PR there will be much opportunity for discussion on all the bits that need updating too, and we definitely want David and Matt's wisdom to be a part of that.

Development has started, but we'll push some WIP PRs as soon as possible so not to spend a bunch of time on something that may or may not be the best D8 way.

**Comment by jackrabbithanna** [comment] 2020-04-02 01:29
@ddoligalski please do make other issues for other Views issues you are dealing with. We need to get them documented, and the squeaky wheel gets the grease. If you need some improved Views integration for specific fields, like ASAP, you can contact me at mark@skvare.com or our account manager gena@skvare.com. This current work is partially funded by some needs of our clients, partially by Skvare itself, and we could get on contract to accelerate your needs. If you have devs that are working on the problems already,  we'll can help or offer guidance to get started to submit patches in this project's issue queue or ping me in the civicrm mattermost chat, civicrm entity channel, https://chat.civicrm.org/civicrm/channels/civicrm-entity.

**Comment by dsnopek** [comment] 2020-04-16 15:12
> Consider that in the D7, custom fields were treated as a separate table, implicitly joined to the appropriate entity type base table, without a Views Relationship.

I suspect this might be a smaller change than @jackrabbithanna is making it out to be? Although, I guess I'd need to see the new code to know for sure.

In the current civicrm_entity 8.x-3.x implementation, it's NOT using Views Relationships for the custom fields, it's actually treating custom fields as properties of the entity - views isn't doing any join at all, implicit or explicit. When showing the fields, it's just getting the property from the loaded entity. The reason filters don't work, is that the default filter implementation for entity properties is to treat them as if they are columns on the entity table, which they aren't in this case.

We definitely still want custom fields to be considered properties of the entity, because that gives us automatic integration with anything that works with the Entity Field API, ex. Rules, jsonapi, etc. And we still want Views to show the fields as entity properties, because then we can apply Drupal field formatters to them, like Drupal users would expect from a View of an entity.

But to make filters work, we'd just want to swap out the default filter handlers with implementations that automatically join against the table that the custom fields really are on!

@jackrabbithanna Is that what you're proposing here? If so, this sounds perfect. :-) If not, I'd really love to see your code, because I don't want us to lose some of the tight integration with the Drupal Entity Field API that we already have.

**Comment by jackrabbithanna** [comment] 2020-04-16 19:07
I've got a working prototype by a developer internally, the PR to show will likely come next week
It is a bit of change ....... we're setting Views integration to work like it did in D7.

This means the main entity type gets joins set in the Views definition to the custom field group table, and the custom group name will show in the "Categories" select box in the header when you add a field/filter etc.. 

We also ported about 4 field plugins and 4-5 filter plugins from D7.Contact Reference, Country, State/Province, Pseudoconstant .. to get feature equivalence from D7

I don't see how the custom fields being associated with the base table will work. All the queries need rewriting for filters, field aggregation wasn't working as it was. 

Instead of a query alter, we went with this because the 
1) It presents an upgrade path from D7 for Views
2) Filter plugins need different exposed filter options lists and things. 
3) All Views stuff "just works" 

It will be a change for people to upgrade CE to this, if they've already got custom fields used in Views.  But that's it .. pull the band aid off once, it needs to be done.

The custom fields remain base fields on the entity.  For all other purposes than Views, nothing changes.       
So entity load programmatically will have the custom field values same, view pages, edit forms, all of that the same. 

PR for review coming soon.

**Comment by jackrabbithanna** [comment] 2020-04-16 19:20
I suppose the only that is different, is being able to use some Drupal field formatters, for custom fields in a View. 
Which existing field formatters do not work for all custom field types / widget types.. 
So on top of the query rewriting, there would need to be additional field formatters. 

The field / filter plugins will work as CiviCRM people are used to them working in Drupal 7 this way..I can see how a pure Drupal person may be disappointed if they can't use their field formatter on a custom field in a View. Of course the new custom field plugins could have additions and improvements, and people could make their own field plugins to use instead.

It's also possible that we could figure out how to apply Drupal field formatters as an option in the new plugins.

**Comment by jackrabbithanna** [comment] 2020-04-17 02:06
Another reason is mulit-valued custom field groups. 

The API doesn't return all the custom field values, if multiple values are allowed for a custom field group. 

You only get the most recent value in an entity_load of a CiviCRM entity with Drupal API

I'm not even sure you can have multiple values for base fields?

Regardless .. unless the join is done to the custom field group table, and the column given a plugin manually .. you can't list multiple values of a custom field per contact. 
If you have a contact where you have a mult-valued group attached, and edit a contact, give it two values for the fields in the group .. you should get two records for that contact in the View .. because the join returns two rows for the custom field table. 

This is not a bug, it's a feature. You can properly filter / aggregate etc.. on those properties. 

If we agree that the custom field tables should be joined to, for this and the other reasons .. Then I think it's just a matter of working together to refine the "how" it is done.

**Comment by jackrabbithanna** [comment] 2020-04-17 02:16
Also to remember:
CiviCRM Core Team has removed the deprecated "CiviCRM Views" module from the Drupal module. CiviCRM Entity is providing Views Integration for CiviCRM / Drupal community moving forward. 

It's up to CE to provide feature parity or better with the D7 version for Views. 

This custom field work we are doing represents about less than half of the work left to be done to get there.

**Comment by jackrabbithanna** [comment] 2020-04-17 15:35
WIP PR for review: https://github.com/eileenmcnaughton/civicrm_entity/pull/210

Tested with each custom field type / widget type combination, on a "normal" instance with civi tables in the Drupal db .. "Round earth-ish" Drupal 8.8 composer install

**Comment by dsnopek** [comment] 2020-04-28 14:41
> I suppose the only that is different, is being able to use some Drupal field formatters, for custom fields in a View.
> Which existing field formatters do not work for all custom field types / widget types..
> So on top of the query rewriting, there would need to be additional field formatters.
>
> The field / filter plugins will work as CiviCRM people are used to them working in Drupal 7 this way..I can see how a pure Drupal person may be disappointed if they can't use their field formatter on a custom field in a View. Of course the new custom field plugins could have additions and improvements, and people could make their own field plugins to use instead.

Well, if the custom fields are still going to be base fields on the Entity, in order to render the Entity, those fields need to pass through field formatters anyway.

So, if the problem is that the field formatters can't correctly render those fields (or can't do so in ways that Civi users expect), it should be fixed at the Entity Field API level, rather than just in the Views integration via Views field handlers.

Said another way:

Each custom field could be configured with the Entity Field API such that all the allowed field formatters for it work, and that all necessary field formatters that Civi folks need are available. This probably requires some custom field types and/or field formatters. But then the Views integration can just let the user pick from the set of available field formatters for rendering those fields. This has the nice side effect that rendering those fields works the same in both places (in Entity rendering and Views) and that it matches the expectations of Drupal users.

**Comment by dsnopek** [comment] 2020-04-28 14:52
> Another reason is mulit-valued custom field groups.
>
> The API doesn't return all the custom field values, if multiple values are allowed for a custom field group.
>
> You only get the most recent value in an entity_load of a CiviCRM entity with Drupal API
>
> I'm not even sure you can have multiple values for base fields?

Entity base fields can have multiple values.

Entities in Drupal 8 don't need to be bound to SQL tables, they can be completely remote and have any kind of definition that can be expressed in TypedData. Currently, civicrm_entity is binding them to SQL so that we can treat the civicrm_* tables like base tables, but it doesn't actually have to work that way. It could have been done entirely on top of `civicrm_api4()` calls or something. The current approach was based on a set of trade-offs that Matt and I discussed with you early on.

In any case, if currently, loading the entity is only returning the most recent value, and we want it to return all values, then that's a bug in the way civicrm_entity is currently loading custom values and can be fixed.

> Regardless .. unless the join is done to the custom field group table, and the column given a plugin manually .. you can't list multiple values of a custom field per contact.
If you have a contact where you have a mult-valued group attached, and edit a contact, give it two values for the fields in the group .. you should get two records for that contact in the View .. because the join returns two rows for the custom field table.

Right, if you want multiple results in the View for each value of the multi-value custom field, then it there has to be join somehow.

However, is it a given that users always want multiple Views results for each value of a custom field?

What if you want to display all the values for that custom field in the same Views result? For example, let's say your generating a table, where each row is a Contact, and you want to show all the values for a specific custom field as an ordered list in one of the columns. That could be done where a single result is returned for that Contact entity, and then a field formatter is used on the custom field to render it as an ordered list.

IMO, switching between a single result for each entity and multiple results for each custom field value should be done by adding a relationship.

**Comment by jackrabbithanna** [comment] 2020-04-28 16:42
> In any case, if currently, loading the entity is only returning the most recent value, and we want it to return all values, then that's a bug in the way civicrm_entity is currently loading custom values and can be fixed.

It's not really a bug, it's just that the a 'get' action with the API will return the latest. To get them all, we have to use a 'CustomValue' API call. Preferably we'd make the base field definition cardinality unlimited for custom fields that are in a  group that allows multiple values. Also load() and save() would need to be updated to fetch the 'get' for the entity type and then for any multi-valued custom group fields, use CustomValue.

I think this would be the long term goal, but for now we're really trying to get the Views functionality done in a way that can handle a future update for custom fields in general when we have a new cycle of budget.

ATM we're working on a field plugin that extends EntityField .. and then trying to override getItems() , createEntityForGroupBy(), and query() methods .. to see if we can keep the tight entity api integration, but not have to dive into the more general update that will be necessary for custom fields.

This would allow the use of field formatters, default multiple value handling .. and still keep filters/sorts/arguments handled the way we did in the PR.

I think that would be a good compromise .. in that all the Views features would work, aggregation, click sorting, and I think "default" multiple values handling .. This would setup the integration so that later, if the base field definitions and load/save gets updated at the "entity level" .. then Views would be setup to just switch to EntityField instead of this custom version...that should be a clean transitions for people, just switching which plugin is used.

> IMO, switching between a single result for each entity and multiple results for each custom field value should be done by adding a relationship.

We're hoping to have the standard field "multiple values" handling working .. where you can configure to output all values in one view's result with a separator .. OR choose to display each value in it's own row. I think this may be achievable without a Views relationship .. the field plugin would do the join in the query() method, depending of field configuration.
A relationship is definitely an option though, and if we can't make this field plugin to work, we can switch to doing that.

I hope to have an update to the PR, or a separate one, so you can see more clearly what I'm trying to describe

**Closed** 2021-01-21 23:10 UTC
