### ISSUE TITLE
Uninstalling CiviCRM Entity

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#185] opened 2019-09-13 23:31 UTC
Deletes data from your CiviCRM tables :-(

Good thing it did not let me delete user 1!

`CiviCRM_API3_Exception: This contact record is linked to the currently logged in user account - and cannot be deleted. in civicrm_api3() (line 45 of /var/www/drupal/vendor/civicrm/civicrm-core/api/api.php).`

But all Contributions on this test site have been deleted - and so have most of the Contacts (until it his this error).

**Comment by jackrabbithanna** [comment] 2019-09-14 18:49
I'm assuming this happens with the patches from the PRs you contributed?

**Comment by KarinG** [comment] 2019-09-14 19:49
Yes. But these patches just help to get to the Uninstall screen.

**Comment by KarinG** [comment] 2019-09-14 20:48
It looks like this:
![image](https://user-images.githubusercontent.com/5340555/64913477-2ad2b500-d6fe-11e9-94ae-c6c1da24aa7f.png)

![image](https://user-images.githubusercontent.com/5340555/64913479-37570d80-d6fe-11e9-88b6-094f606a2bae.png)

And yes that has now deleted all my Tags from CiviCRM

Note - uninstalling via drush -> is essentially the same:
```
root@9f03c6ef5d47:/var/www/drupal/web# drush pm:uninstall civicrm_entity
In PmCommands.php line 129:
                                                                                                                  
civicrm_entity: There is content for the entity type: CiviCRM Group. <a href="/admin/modules/uninstall/entity/civicrm_custom_group">Remove civicrm group entities</a>.  
```

**Comment by jackrabbithanna** [comment] 2019-09-16 11:56
Obviously we don't want ANY data removed on module uninstall. Let's just document expected behavior. 

1) No civicrm data is removed from CiviCRM tables
2) Any Drupal fields added to the entity should have their Drupal db tables removed, and fields removed from configuration. Any of the entity type view modes etc.. removed..

This will again be custom behavior for a Drupal entity type. 

We should dig into the process that Drupal is running by default, and override methods as appropriate to get the desired behavior we want.

You can "disable" the module like this, in the meantime:
drush eval "\$module_data = \Drupal::config('core.extension')->get('module'); unset(\$module_data['civicrm_entity'']); \Drupal::configFactory()->getEditable('core.extension')->set('module', \$module_data)->save();"

**Comment by KarinG** [comment] 2020-08-27 00:48
@jackrabbithanna - I ran into this issue again. This time I can't nuke the site and restart.

So I'm trying the drush commands you posted but that produces a syntax error. 
`[error]  ParseError: syntax error, unexpected '=',`

**Comment by jackrabbithanna** [comment] 2020-08-27 13:45
Make sure there's no whitespace in the command .. so that no return carriage between the opening double quote and the closing one at the end.

It will work. 

Once you get it "disabled" .. then you can delete the CE configuration entity that it has for the settings and it will be as if CE was not installed.

**Comment by KarinG** [comment] 2020-08-27 13:52
I do have it all on one line - no carriage returns:

![image](https://user-images.githubusercontent.com/5340555/91450936-1b2e7c80-e83a-11ea-8ba0-fc1d91123893.png)

**Comment by jackrabbithanna** [comment] 2020-08-27 15:08
Try this:
drush eval "\$module_data = \Drupal::config('core.extension')->get('module'); unset(\$module_data['MODULE_NAME']); \Drupal::configFactory()->getEditable('core.extension')->set('module', \$module_data)->save();"

**Comment by jackrabbithanna** [comment] 2020-08-27 15:08
Ooh I see the problem Github is editing out some of it:
`drush eval "\$module_data = \Drupal::config('core.extension')->get('module'); unset(\$module_data['MODULE_NAME']); \Drupal::configFactory()->getEditable('core.extension')->set('module', \$module_data)->save();"`

**Comment by KarinG** [comment] 2020-08-27 15:34
Yes bingo! :-) Thanks Mark

**Comment by KarinG** [comment] 2020-08-27 16:05
And then (Pradeep) -> 
DELETE * FROM config WHERE name LIKE "civicrm_entity.settings%";

**Comment by KarinG** [comment] 2020-09-04 17:18
Hi @jackrabbithanna - These two steps still did not completely uninstall CiviCRM Entity -> 

1. In the Uninstall Tab -> CiviCRM still says CiviCRM Entity is installed

2. root@52b4c507e3f3:/var/www/drupal# drush cr

In DiscoveryTrait.php line 53:
                                                                                                                                                     
  The "entity:civicrm_address" plugin does not exist. Valid plugin IDs for Drupal\views\Plugin\ViewsPluginManager are: entity_reference_revisions,   
  leaflet_marker, entity:node, node_rss, search_view, entity:user, entity_reference, entity:block_content, entity:file, entity:media, entity:path_a  
  lias, entity:webform_submission, entity:paragraph, fields, opml_fields, rss_fields

**Comment by jackrabbithanna** [comment] 2020-09-04 20:46
Yeah you'd have to manually remove Views that use CE fields .. this is not a proper uninstall measure. It's a workaround until one day we have a real one.

**Comment by KarinG** [comment] 2020-09-05 03:07
Tried to install all views but that did not work

```
root@52b4c507e3f3:/var/www/drupal/web/sites# drush pm:uninstall views
The following extensions will be uninstalled: views, views_ui, leaflet_views, slick_views, views_bootstrap, views_infinite_scroll, webform_views

 Do you want to continue? (yes/no) [yes]:
 > yes

In EntityTypeManager.php line 150:
                                                          
  The "civicrm_custom_field" entity type does not exist.  
```

**Comment by Panther09** [comment] 2020-09-14 05:09
I'm not sure if this the right place to post this. I ran into this post because I thought uninstalling CiviCRM Entity would be an easy solution to my real problem. But obviously it's not. Actually I would like to keep CiviCRM Entity but to get rid of the error messages I get on my status report after updating some drupal modules (I'm not quite sure which because I saw this message a while later). 

" Non-matching entity and/or field definitions.
The following changes to the entity types and field definitions were found:
Contact CiviCRM

    The CiviCRM ID field must be updated.
    The Contact Type field needs to be updated.
..."
(and many more)

Actually the second part of the error message (the hint to the single fields) is the result of my attempt to solve the problem by running "drush entup", before, the messages referred only to the entity types.

Do you know of a way to solve this or a more proper place to post this.

Thanks a very lot.

**Comment by jackrabbithanna** [comment] 2020-09-14 12:44
Yep those errors on status, we see too. running 'drush entup' creates tables in the Drupal database that mimic the civicrm database (we run separate dbs). We haven't seen any harm from them, but they are very visually present on that page. 
It's Drupal Core that is producing those messages.

**Comment by Panther09** [comment] 2020-09-14 15:27
Thanks a lot. That helps me to relax and just to leave everything as it is.

**Comment by stesi561** [comment] 2020-10-28 03:12
Confirming this is still a problem with the 8.x-3.x branch. Luckily discovered via a dev site.

**Comment by jackrabbithanna** [comment] 2020-11-09 19:31
A WIP PR here if people want to test: https://github.com/eileenmcnaughton/civicrm_entity/pull/255
Don't try on production sites.

**Comment by KarinG** [comment] 2020-11-14 20:05
Has anyone tried #255 yet? I'm too scared :-)

**Comment by jackrabbithanna** [comment] 2021-01-21 23:09
This PR is merged. Considering issues resolved

**Closed by jackrabbithanna** 2021-01-21 23:09 UTC
