### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by HeneryH** [eileenmcnaughton/civicrm_entity#221] opened 2020-07-13 19:23 UTC
```
$ composer create-project drupal/recommended-project:8.9.2 /var/www/drupal --no-interaction
$
$ composer global require drush/drush:"9.*"
$
$ composer require civicrm/civicrm-asset-plugin civicrm/civicrm-{core,packages,drupal-8}:"^5.27"
$
$ composer config repositories.civicrm_entity vcs https://github.com/eileenmcnaughton/civicrm_entity
$
$ composer require drupal/civicrm_entity:3.x-dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for drupal/civicrm_entity 3.x-dev -> satisfiable by drupal/civicrm_entity[3.x-dev].
    - drupal/civicrm_entity 3.x-dev requires drupal/civicrm * -> no matching package found.
```

composer.json
```
{
    "name": "drupal/recommended-project",
    "description": "Project template for Drupal 8 projects with a relocated document root",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "homepage": "https://www.drupal.org/project/drupal",
    "support": {
        "docs": "https://www.drupal.org/docs/user_guide/en/index.html",
        "chat": "https://www.drupal.org/node/314178"
    },
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "civicrm_entity": {
            "type": "vcs",
            "url": "https://github.com/eileenmcnaughton/civicrm_entity"
        }
    },
    "require": {
        "civicrm/civicrm-asset-plugin": "^1.0",
        "civicrm/civicrm-core": "^5.27",
        "civicrm/civicrm-drupal-8": "^5.27",
        "civicrm/civicrm-packages": "^5.27",
        "composer/installers": "^1.2",
        "drupal/core-composer-scaffold": "^8.8",
        "drupal/core-project-message": "^8.8",
        "drupal/core-recommended": "^8.8"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    },
    "extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "web/"
            }
        },
        "installer-paths": {
            "web/core": [
                "type:drupal-core"
            ],
            "web/libraries/{$name}": [
                "type:drupal-library"
            ],
            "web/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "web/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "web/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "drush/Commands/contrib/{$name}": [
                "type:drupal-drush"
            ],
            "web/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "web/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ]
        },
        "drupal-core-project-message": {
            "include-keys": [
                "homepage",
                "support"
            ],
            "post-create-project-cmd-message": [
                "<bg=blue;fg=white>                                                         </>",
                "<bg=blue;fg=white>  Congratulations, you’ve installed the Drupal codebase  </>",
                "<bg=blue;fg=white>  from the drupal/recommended-project template!          </>",
                "<bg=blue;fg=white>                                                         </>",
                "",
                "<bg=yellow;fg=black>Next steps</>:",
                "  * Install the site: https://www.drupal.org/docs/8/install",
                "  * Read the user guide: https://www.drupal.org/docs/user_guide/en/index.html",
                "  * Get support: https://www.drupal.org/support",
                "  * Get involved with the Drupal community:",
                "      https://www.drupal.org/getting-involved",
                "  * Remove the plugin that prints this message:",
                "      composer remove drupal/core-project-message"
            ]
        }
    }
}
```

**Comment by stesi561** [comment] 2020-10-24 04:16
This seems to be a duplicate of this -> https://www.drupal.org/project/civicrm_entity/issues/3031344 which is resolved so this could probably be closed.

**Comment by jackrabbithanna** [comment] 2021-01-21 23:11
Updates coming in beta2 if not there already

**Closed by jackrabbithanna** 2021-01-21 23:11 UTC
